### ISSUE TITLE
"Call to member function 'send' is ambiguous" error

### ISSUE THREAD

**Issue by ryohajika** [2bbb/ofxZeroMQ#1]
Thank you for making this addon! It is cool to see how it was implemented.
I'm trying to use the zmq connection to send a message in protobuf format.
When I try the code in below, I get the error mentioned as the topic title.

```
// (in ofApp::update())
size_t pbuf_size = pbuf_blob.ByteSizeLong(); // pbuf_blob is a message object of protobuf
char * pbuf_buf = new char[pbuf_size];
pbuf_blob.SerializeToArray(pbuf_buf, pbuf_size);
pub.send(pbuf_buf, pbuf_size); // this is the line where I get an error "Call to member function 'send' is ambiguous
```

It would be great if you can give me any suggestion to solve the error problem about this.
Arigatogozaimasu!

**Comment by 2bbb** [comment]
@ryohajika 
what's env on?

**Comment by ryohajika** [comment]
it's OSX 10.15.5, Xcode 11.5 and of_0.11.0_osx_release

**Comment by 2bbb** [comment]
i don't t test this code, but, maybe,  don't you get right with below?:

```
pub.send((void *)pbuf_buf, pbuf_size);
```

**Comment by ryohajika** [comment]
it gives me the same error message...
I'm just wondering it could be because of the definition style, since the latest version of Xcode giving me random errors on the definition or header loading style.

**Comment by 2bbb** [comment]
sorry, i missed. please try below:

```
pub.send((const void *)pbuf_buf, pbuf_size);
```

**Comment by ryohajika** [comment]
it's working now! thanks a lot.
btw do you think is the implementation safe? especially the part keeps allocating the space by:
```
char * pbuf_buf = new char[pbuf_size];
```
in every ofApp::update()

**Comment by 2bbb** [comment]
@ryohajika 
you need to do `delete[] pbuf_buf;` after `send`.

**Comment by 2bbb** [comment]
@ryohajika 

i fixed that problem (`send(const void *, size_t)` is ambiguous).
please check latest master without casting with `(const void*)`.
